[workspace]
default-members = [
    "ristretto_classfile",
    "ristretto_classloader",
]
members = [
    "examples/*",
    "ristretto_classfile",
    "ristretto_classloader",
]
resolver = "2"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["development-tools"]
edition = "2021"
keywords = ["java", "jvm"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/theseus-rs/ristretto"
version = "0.4.0"

[workspace.dependencies]
anyhow = "1.0.44"
bitflags = "2.6.0"
byteorder = "1.5.0"
criterion = { version = "0.5.1", default-features = false }
dashmap = "6.0.1"
flate2 = "1.0.31"
indoc = "2.0.5"
rayon = "1.10.0"
reqwest = "0.12.5"
tar = "0.4.41"
thiserror = "1.0.63"
tokio = { version = "1.39.2", default-features = false, features = ["macros", "rt", "sync"] }
tracing = "0.1.40"
zip = { version = "2.1.6", default-features = false, features = ["deflate"] }

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
