[workspace]
default-members = [
    "ristretto_classfile"
]
members = [
    "examples/*",
    "ristretto_classfile",
]
resolver = "2"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["development-tools"]
edition = "2021"
keywords = ["java", "jvm"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/theseus-rs/ristretto"
version = "0.2.2"

[workspace.dependencies]
bitflags = "2.6.0"
byteorder = "1.5.0"
criterion = "0.5.1"
flate2 = "1.0.30"
indoc = "2.0.5"
reqwest = "0.12.5"
tar = "0.4.41"
thiserror = "1.0.61"
tokio = "1.38.0"
zip = "2.1.3"

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"
