[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.26.1"
# CI backends to support
ci = "github"
# Whether dist should create a Github Release or use an existing draft
create-release = false
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# Post-announce jobs to run in CI
post-announce-jobs = ["./release-post-announce"]
# Which actions to run on pull requests
pr-run-mode = "upload"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "theseus-rs/homebrew-tap"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-pc-windows-msvc", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]

[dist.github-custom-runners]
aarch64-apple-darwin = "macos-15"
