[package]
edition.workspace = true
name = "read_class"
publish = false
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
ristretto_classfile = { path = "../../ristretto_classfile" }
