[package]
name = "ristretto_fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ristretto_classfile = { path = "../ristretto_classfile" }

[[bin]]
name = "mutf8_from_bytes"
path = "fuzz_targets/mutf8_from_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mutf8_to_bytes"
path = "fuzz_targets/mutf8_to_bytes.rs"
test = false
doc = false
bench = false
