[package]
edition.workspace = true
license.workspace = true
name = "ristretto_fuzz"
publish = false
repository.workspace = true
version.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ristretto_classfile = { path = "../ristretto_classfile" }

[[bin]]
name = "mutf8_from_bytes"
path = "fuzz_targets/mutf8_from_bytes.rs"

[[bin]]
name = "mutf8_to_bytes"
path = "fuzz_targets/mutf8_to_bytes.rs"
