[package]
authors.workspace = true
categories.workspace = true
description = "A library for loading Java classes."
edition.workspace = true
keywords = ["java", "jvm", "classloader", "class", ]
license.workspace = true
name = "ristretto_classloader"
repository.workspace = true
version.workspace = true

[dependencies]
dashmap = { workspace = true, features = ["rayon"] }
flate2 = { workspace = true }
rayon = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
ristretto_classfile = { path = "../ristretto_classfile", version = "0.5.0" }
serde = { workspace = true, features = ["derive"] }
tar = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zip = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
home = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
criterion = { workspace = true }
indoc = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
tokio = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }

[features]
all = ["url"]
default = []
url = []

[[bench]]
harness = false
name = "class_loader"
