[package]
authors.workspace = true
categories.workspace = true
description = "Java Virtual Machine"
edition.workspace = true
keywords = ["java", "jvm"]
license.workspace = true
name = "ristretto_vm"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-recursion = { workspace = true }
bitflags = { workspace = true }
byte-unit = { workspace = true }
dashmap = { workspace = true }
dirs = { workspace = true }
indexmap = { workspace = true }
os_info = { workspace = true }
ristretto_classfile = { path = "../ristretto_classfile", version = "0.13.0" }
ristretto_classloader = { path = "../ristretto_classloader", version = "0.13.0" }
stacker = { workspace = true }
sysinfo = { workspace = true }
sys-locale = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
whoami = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }
tokio = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = { workspace = true }
home = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
criterion = { workspace = true }

[features]
default = ["rustls-tls"]
native-tls = [
    "ristretto_classloader/native-tls",
]
rustls-tls = [
    "ristretto_classloader/rustls-tls",
]
url = [
    "ristretto_classloader/url",
]

[[bench]]
harness = false
name = "vm"
