name: fuzz

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 12 * * 0'

permissions:
  contents: read

jobs:
  fuzz:
    name: ${{ matrix.test }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        test:
          - mutf8_from_bytes
          - mutf8_to_bytes

        include:
          - test: mutf8_from_bytes
            runs: 1000000
          - test: mutf8_to_bytes
            runs: 1000000

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Install cargo fuzz
        uses: dtolnay/install@cargo-fuzz

      - name: Fuzz Tests
        env:
          CARGO_TERM_COLOR: always
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUST_LOG: "info"
          RUST_LOG_SPAN_EVENTS: full
        run: |
          cargo fuzz run ${{ matrix.test }} -- -runs=${{ matrix.runs }}
